# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.destroy_all
Message.destroy_all

user1 = User.create(first_name: "Bob", last_name:"Tester", username: "Bobbob", email: "bob@bob.com", age: 22, gender: "Male", location: "London", plan: "standard", password: "bob12345", confirmed_at: DateTime.now)
user2 = User.create(first_name: "Alice", last_name:"Tester", username: "Alice1986", email: "alice@alice.com", age: 20, gender: "Female", location: "Oxford", plan: "premium", password: "alice12345", confirmed_at: DateTime.now)
user3 = User.create(first_name: "Kate", last_name:"Tester", username:"CrazyKate", email: "kate@kate.com", age: 21, gender: "Female", location: "London", plan: "standard", password: "kate12345", confirmed_at: DateTime.now)

# user1.plan = "standard"
# user2.plan = "premium"
# user3.plan = "premium"
# Bob messages Alice
message1 = Message.create(sender_id: user1.id, recipient_id: user2.id, content: "Hello Alice, from Bob")
# Alice messages Bob
message2 = Message.create(sender_id: user2.id, recipient_id: user1.id, content: "Hello Bob, from Alice")
# Alice also messages Kate
message3 = Message.create(sender_id: user2.id, recipient_id: user3.id, content: "Hello Kate, from Alice")


# Bob has 2 messages (1 sent to Alice, 1 from Alice)
# Alice has 3 messages (1 from Bob, 1 to Bob, 1 to Kate)
# Kate has 1 message (1 from Alice)

# user2.all_messages.length == 3 # TRUE
# user2.messages_with_user(user1.id).length == 2   # TRUE

# Event tests

# Bob stars Alice
event = Event.create(user_id: user1.id, target_user_id: user2.id, event_type: 'star', created_at: DateTime.now)
# Alice pokes Bob
event2 = Event.create(user_id: user2.id, target_user_id: user1.id, event_type: 'poke', created_at: DateTime.now)


userah = User.create(first_name: "Alex", last_name:"Hamlin", username: "AlexH", email: "alex@alex.com", age: 29, gender: "Male", location: "London", plan: "premium", password: "password", confirmed_at: DateTime.now, tagline: "If you live near Clapham you could do a lot worse.", bio: "Hey, I'm Alex. I have impeccably gelled hair every day, and my wardrobe of coloured trousers will dazzle you.", avatar: "https://s3-eu-west-1.amazonaws.com/wdi-dating-production/uploads/static/gallery_ga_200x200_02.jpg?AWSAccessKeyId=ASIAJPBDBTBJLCJG6F5Q&Expires=1385050067&Signature=XmkYxcJ3Bh82nZnwfzu15nrXcW4%3D&x-amz-security-token=AQoDYXdzENf//////////wEawAIsrHO97KTEcDp4VTgsK9eAevLfqg5Js7vd%2BUbaraYA6adb6lIiXIyI8abnY4%2B3z6FktlO3McGF8vpqkz4f9ZVGpL3yS2AzLiXd844X2rw%2B%2BmehBVyfXA1o1dMftl50cyghdtVxA/N5xrBCFTbXIPzCclniuGHIFdHjtJZsEZ10AHRbVsYCI7R5%2BmCDYP4/irsVg7Jw%2BFGmSm1L29pwCmjRSw%2BvxcnRf8m6enXob9O2a8OoKkElJC2vbsOzlsclb6gaDfrpC1lLz5TDUdtuY9cuvHNN7E9GXn3ikG9/UtRxwFlpFjoPH%2Ba2XK42xIRb3nDvq2SEyje0WVcpKpImYNcQlKAzCCGWwhtvbArrBFo7ltEZZzoo/LzKox4TwvHxRfWQ1/a14ifuQXzYyEXD9fEfs06hMEnKw38sZgpwEjJfIiDTm7iUBQ%3D%3D")
userah.save!

userja = User.create(first_name: "Jonny", last_name:"Adshead", username: "Jonny", email: "jonny@jonny.com", age: 24, gender: "Male", location: "London", plan: "premium", password: "password", confirmed_at: DateTime.now, tagline: "I've got a girlfriend, so...", bio:     "Ask me to make any sound and I'll reproduce it using my vocal chords. Then, we can talk about music :)", avatar: "https://s3-eu-west-1.amazonaws.com/wdi-dating-production/uploads/static/gallery_ga_200x200_03.jpg?AWSAccessKeyId=ASIAJPBDBTBJLCJG6F5Q&Expires=1385050216&Signature=7oXgpLQjKnLxL3wgU8w3KPT3lK4%3D&x-amz-security-token=AQoDYXdzENf//////////wEawAIsrHO97KTEcDp4VTgsK9eAevLfqg5Js7vd%2BUbaraYA6adb6lIiXIyI8abnY4%2B3z6FktlO3McGF8vpqkz4f9ZVGpL3yS2AzLiXd844X2rw%2B%2BmehBVyfXA1o1dMftl50cyghdtVxA/N5xrBCFTbXIPzCclniuGHIFdHjtJZsEZ10AHRbVsYCI7R5%2BmCDYP4/irsVg7Jw%2BFGmSm1L29pwCmjRSw%2BvxcnRf8m6enXob9O2a8OoKkElJC2vbsOzlsclb6gaDfrpC1lLz5TDUdtuY9cuvHNN7E9GXn3ikG9/UtRxwFlpFjoPH%2Ba2XK42xIRb3nDvq2SEyje0WVcpKpImYNcQlKAzCCGWwhtvbArrBFo7ltEZZzoo/LzKox4TwvHxRfWQ1/a14ifuQXzYyEXD9fEfs06hMEnKw38sZgpwEjJfIiDTm7iUBQ%3D%3D")
userja.save!

userjl = User.create(first_name: "Jack", last_name:"Lalley", username: "Jack", email: "jack@jack.com", age: 18, gender: "Male", location: "London", plan: "premium", password: "password", confirmed_at: DateTime.now, tagline: "It would be  better if everyone just did it my way.", bio: "This site is rubbish. Why didn't you just do it like I said? Also...has anyone seen my bottle cap?", avatar: "https://s3-eu-west-1.amazonaws.com/wdi-dating-production/uploads/static/gallery_ga_200x200_04.jpg?AWSAccessKeyId=ASIAJPBDBTBJLCJG6F5Q&Expires=1385050280&Signature=CImgBkadSINAE7sWgdXB6Qh5/tw%3D&x-amz-security-token=AQoDYXdzENf//////////wEawAIsrHO97KTEcDp4VTgsK9eAevLfqg5Js7vd%2BUbaraYA6adb6lIiXIyI8abnY4%2B3z6FktlO3McGF8vpqkz4f9ZVGpL3yS2AzLiXd844X2rw%2B%2BmehBVyfXA1o1dMftl50cyghdtVxA/N5xrBCFTbXIPzCclniuGHIFdHjtJZsEZ10AHRbVsYCI7R5%2BmCDYP4/irsVg7Jw%2BFGmSm1L29pwCmjRSw%2BvxcnRf8m6enXob9O2a8OoKkElJC2vbsOzlsclb6gaDfrpC1lLz5TDUdtuY9cuvHNN7E9GXn3ikG9/UtRxwFlpFjoPH%2Ba2XK42xIRb3nDvq2SEyje0WVcpKpImYNcQlKAzCCGWwhtvbArrBFo7ltEZZzoo/LzKox4TwvHxRfWQ1/a14ifuQXzYyEXD9fEfs06hMEnKw38sZgpwEjJfIiDTm7iUBQ%3D%3D")
userjl.save!

useraf = User.create(first_name: "Alex", last_name:"Fasanmade", username: "AlexF", email: "alexf@alexf.com", age: 28, gender: "Male", location: "London", plan: "premium", password: "password", confirmed_at: DateTime.now, tagline: "I like formal education, cassava and leather jackets.", bio:     "Hi, I'm Alex. Looking for a non-violent Nigerian Pprincess to organise my copious notes. Only Oxford-rule notebooks, please.", avatar: "https://s3-eu-west-1.amazonaws.com/wdi-dating-production/uploads/static/gallery_ga_200x200_05.jpg?AWSAccessKeyId=ASIAJPBDBTBJLCJG6F5Q&Expires=1385050335&Signature=vxooyezPY5V0%2BMa8xJLLWhuIedM%3D&x-amz-security-token=AQoDYXdzENf//////////wEawAIsrHO97KTEcDp4VTgsK9eAevLfqg5Js7vd%2BUbaraYA6adb6lIiXIyI8abnY4%2B3z6FktlO3McGF8vpqkz4f9ZVGpL3yS2AzLiXd844X2rw%2B%2BmehBVyfXA1o1dMftl50cyghdtVxA/N5xrBCFTbXIPzCclniuGHIFdHjtJZsEZ10AHRbVsYCI7R5%2BmCDYP4/irsVg7Jw%2BFGmSm1L29pwCmjRSw%2BvxcnRf8m6enXob9O2a8OoKkElJC2vbsOzlsclb6gaDfrpC1lLz5TDUdtuY9cuvHNN7E9GXn3ikG9/UtRxwFlpFjoPH%2Ba2XK42xIRb3nDvq2SEyje0WVcpKpImYNcQlKAzCCGWwhtvbArrBFo7ltEZZzoo/LzKox4TwvHxRfWQ1/a14ifuQXzYyEXD9fEfs06hMEnKw38sZgpwEjJfIiDTm7iUBQ%3D%3D")
useraf.save!

usersc = User.create(first_name: "Selina", last_name:"Chotai", username: "Selina", email: "selina@selina.com", age: 28, gender: "Female", location: "London", plan: "premium", password: "password", confirmed_at: DateTime.now, tagline:     "Pass me the pesto-jam porridge, I'm running late for class!", bio:     "Hi, I'm Selina and I love an interesting brunch item. When it comes to brunch, the later the better - once, I had brunch at 3pm and no-one batted an eyelid. Fab! Looking for a man who lives predominantly in the Southern hemisphere.", avatar: "https://s3-eu-west-1.amazonaws.com/wdi-dating-production/uploads/static/gallery_ga_200x200_06.jpg?AWSAccessKeyId=ASIAJPBDBTBJLCJG6F5Q&Expires=1385050355&Signature=lhXBXkeyvI%2B2jmVLdkMmRsg9VKk%3D&x-amz-security-token=AQoDYXdzENf//////////wEawAIsrHO97KTEcDp4VTgsK9eAevLfqg5Js7vd%2BUbaraYA6adb6lIiXIyI8abnY4%2B3z6FktlO3McGF8vpqkz4f9ZVGpL3yS2AzLiXd844X2rw%2B%2BmehBVyfXA1o1dMftl50cyghdtVxA/N5xrBCFTbXIPzCclniuGHIFdHjtJZsEZ10AHRbVsYCI7R5%2BmCDYP4/irsVg7Jw%2BFGmSm1L29pwCmjRSw%2BvxcnRf8m6enXob9O2a8OoKkElJC2vbsOzlsclb6gaDfrpC1lLz5TDUdtuY9cuvHNN7E9GXn3ikG9/UtRxwFlpFjoPH%2Ba2XK42xIRb3nDvq2SEyje0WVcpKpImYNcQlKAzCCGWwhtvbArrBFo7ltEZZzoo/LzKox4TwvHxRfWQ1/a14ifuQXzYyEXD9fEfs06hMEnKw38sZgpwEjJfIiDTm7iUBQ%3D%3D")
usersc.save!

usergm = User.create(first_name: "Geraud", last_name:"Mathe", username: "Geraud", email: "geraud@geraud.com", age: 26, gender: "Male", location: "London", plan: "premium", password: "password", confirmed_at: DateTime.now, tagline: "Boom!", bio: "I'm only on here to cure my infatuation with Dr Chambers.",   avatar: "https://s3-eu-west-1.amazonaws.com/wdi-dating-production/uploads/static/gallery_ga_200x200_07.jpg?AWSAccessKeyId=ASIAJPBDBTBJLCJG6F5Q&Expires=1385050385&Signature=1PNpn4EBDyVDjP78/Y2JS16h%2B0c%3D&x-amz-security-token=AQoDYXdzENf//////////wEawAIsrHO97KTEcDp4VTgsK9eAevLfqg5Js7vd%2BUbaraYA6adb6lIiXIyI8abnY4%2B3z6FktlO3McGF8vpqkz4f9ZVGpL3yS2AzLiXd844X2rw%2B%2BmehBVyfXA1o1dMftl50cyghdtVxA/N5xrBCFTbXIPzCclniuGHIFdHjtJZsEZ10AHRbVsYCI7R5%2BmCDYP4/irsVg7Jw%2BFGmSm1L29pwCmjRSw%2BvxcnRf8m6enXob9O2a8OoKkElJC2vbsOzlsclb6gaDfrpC1lLz5TDUdtuY9cuvHNN7E9GXn3ikG9/UtRxwFlpFjoPH%2Ba2XK42xIRb3nDvq2SEyje0WVcpKpImYNcQlKAzCCGWwhtvbArrBFo7ltEZZzoo/LzKox4TwvHxRfWQ1/a14ifuQXzYyEXD9fEfs06hMEnKw38sZgpwEjJfIiDTm7iUBQ%3D%3D")
usergm.save!

userwb = User.create(first_name: "Winna", last_name:"Bridgewater", username: "Winna", email: "winna@winna.com", age: 30, gender: "Female", location: "London", plan: "premium", password: "password", confirmed_at: DateTime.now, tagline: "Just kidding!", bio:
    "Hey, I have a question...aaand I just answered my own question! Looking for someone who has a really, really big...bag - because I have a lot of $h*t to carry.",   avatar: "https://s3-eu-west-1.amazonaws.com/wdi-dating-production/uploads/static/gallery_ga_200x200_08.jpg?AWSAccessKeyId=ASIAJPBDBTBJLCJG6F5Q&Expires=1385050436&Signature=rIo0q071l3D6POu%2BDoLek7FneGc%3D&x-amz-security-token=AQoDYXdzENf//////////wEawAIsrHO97KTEcDp4VTgsK9eAevLfqg5Js7vd%2BUbaraYA6adb6lIiXIyI8abnY4%2B3z6FktlO3McGF8vpqkz4f9ZVGpL3yS2AzLiXd844X2rw%2B%2BmehBVyfXA1o1dMftl50cyghdtVxA/N5xrBCFTbXIPzCclniuGHIFdHjtJZsEZ10AHRbVsYCI7R5%2BmCDYP4/irsVg7Jw%2BFGmSm1L29pwCmjRSw%2BvxcnRf8m6enXob9O2a8OoKkElJC2vbsOzlsclb6gaDfrpC1lLz5TDUdtuY9cuvHNN7E9GXn3ikG9/UtRxwFlpFjoPH%2Ba2XK42xIRb3nDvq2SEyje0WVcpKpImYNcQlKAzCCGWwhtvbArrBFo7ltEZZzoo/LzKox4TwvHxRfWQ1/a14ifuQXzYyEXD9fEfs06hMEnKw38sZgpwEjJfIiDTm7iUBQ%3D%3D")
userwb.save!

userop = User.create(first_name: "Oli", last_name:"Peate", username: "Oli", email: "oli@oli.com", age: 27, gender: "Male", location: "London", plan: "premium", password: "password", confirmed_at: DateTime.now, tagline: "Shairf, this is not rocket science.", bio: "Let's go out for Italian food and get away from this guy who keeps asking me how to search in Sublime...", avatar: "https://s3-eu-west-1.amazonaws.com/wdi-dating-production/uploads/static/gallery_ga_200x200_09.jpg?AWSAccessKeyId=ASIAJPBDBTBJLCJG6F5Q&Expires=1385050470&Signature=GGWuG/j5VnOo1hZaYDq9csnSFxE%3D&x-amz-security-token=AQoDYXdzENf//////////wEawAIsrHO97KTEcDp4VTgsK9eAevLfqg5Js7vd%2BUbaraYA6adb6lIiXIyI8abnY4%2B3z6FktlO3McGF8vpqkz4f9ZVGpL3yS2AzLiXd844X2rw%2B%2BmehBVyfXA1o1dMftl50cyghdtVxA/N5xrBCFTbXIPzCclniuGHIFdHjtJZsEZ10AHRbVsYCI7R5%2BmCDYP4/irsVg7Jw%2BFGmSm1L29pwCmjRSw%2BvxcnRf8m6enXob9O2a8OoKkElJC2vbsOzlsclb6gaDfrpC1lLz5TDUdtuY9cuvHNN7E9GXn3ikG9/UtRxwFlpFjoPH%2Ba2XK42xIRb3nDvq2SEyje0WVcpKpImYNcQlKAzCCGWwhtvbArrBFo7ltEZZzoo/LzKox4TwvHxRfWQ1/a14ifuQXzYyEXD9fEfs06hMEnKw38sZgpwEjJfIiDTm7iUBQ%3D%3D")
userop.save!

usersch = User.create(first_name: "Sophie", last_name:"Chitty", username: "Sophie", email: "sophie@sophie.com", age: 26, gender: "Female", location: "London", plan: "premium", password: "password", confirmed_at: DateTime.now, tagline: "Amazing", bio:
    "Sophie was too humble to write her own bio, so she asked a passing stranger to write it. After only knowing her for a few seconds, I can honestly say, hand on heart, that she is just the best person I'll ever meet; so cool and great. Really, really, really fantastic.", avatar: "https://s3-eu-west-1.amazonaws.com/wdi-dating-production/uploads/static/gallery_ga_200x200_10.jpg?AWSAccessKeyId=ASIAJPBDBTBJLCJG6F5Q&Expires=1385050502&Signature=N40MF9R02D4hRVyh0HWxoZrYCvY%3D&x-amz-security-token=AQoDYXdzENf//////////wEawAIsrHO97KTEcDp4VTgsK9eAevLfqg5Js7vd%2BUbaraYA6adb6lIiXIyI8abnY4%2B3z6FktlO3McGF8vpqkz4f9ZVGpL3yS2AzLiXd844X2rw%2B%2BmehBVyfXA1o1dMftl50cyghdtVxA/N5xrBCFTbXIPzCclniuGHIFdHjtJZsEZ10AHRbVsYCI7R5%2BmCDYP4/irsVg7Jw%2BFGmSm1L29pwCmjRSw%2BvxcnRf8m6enXob9O2a8OoKkElJC2vbsOzlsclb6gaDfrpC1lLz5TDUdtuY9cuvHNN7E9GXn3ikG9/UtRxwFlpFjoPH%2Ba2XK42xIRb3nDvq2SEyje0WVcpKpImYNcQlKAzCCGWwhtvbArrBFo7ltEZZzoo/LzKox4TwvHxRfWQ1/a14ifuQXzYyEXD9fEfs06hMEnKw38sZgpwEjJfIiDTm7iUBQ%3D%3D")
usersch.save!

userns = User.create(first_name: "Neha", last_name:"Shah", username: "Neha", email: "neha@neha.com", age: 25, gender: "Female", location: "London", plan: "premium", password: "password", confirmed_at: DateTime.now, tagline: "A.K.A Meme Queen", bio:  "Do you have an owl? I really want to hold an owl. There's a place in Scotland you go where they let you hold owls. Want to go there?", avatar: "https://s3-eu-west-1.amazonaws.com/wdi-dating-production/uploads/static/gallery_ga_200x200_11.jpg?AWSAccessKeyId=ASIAJPBDBTBJLCJG6F5Q&Expires=1385050535&Signature=rXRhTYbQ/VFMRH4CUYs0/D3CBlY%3D&x-amz-security-token=AQoDYXdzENf//////////wEawAIsrHO97KTEcDp4VTgsK9eAevLfqg5Js7vd%2BUbaraYA6adb6lIiXIyI8abnY4%2B3z6FktlO3McGF8vpqkz4f9ZVGpL3yS2AzLiXd844X2rw%2B%2BmehBVyfXA1o1dMftl50cyghdtVxA/N5xrBCFTbXIPzCclniuGHIFdHjtJZsEZ10AHRbVsYCI7R5%2BmCDYP4/irsVg7Jw%2BFGmSm1L29pwCmjRSw%2BvxcnRf8m6enXob9O2a8OoKkElJC2vbsOzlsclb6gaDfrpC1lLz5TDUdtuY9cuvHNN7E9GXn3ikG9/UtRxwFlpFjoPH%2Ba2XK42xIRb3nDvq2SEyje0WVcpKpImYNcQlKAzCCGWwhtvbArrBFo7ltEZZzoo/LzKox4TwvHxRfWQ1/a14ifuQXzYyEXD9fEfs06hMEnKw38sZgpwEjJfIiDTm7iUBQ%3D%3D")
userns.save!

userdg = User.create(first_name: "David", last_name:"Grilli", username: "David", email: "david@david.com", age: 26, gender: "Male", location: "London", plan: "premium", password: "password", confirmed_at: DateTime.now, tagline: "Code-lover as well as Latin Lover", bio:   "You like cookies? Great! We can eat them for breakfast. I'll do my movie voice and it will feel pretty epic. Looking for a lady who can throw her head back and laugh heartily, just like me. When we do it together everyone will think we're unstoppable.", avatar: "https://s3-eu-west-1.amazonaws.com/wdi-dating-production/uploads/static/gallery_ga_200x200_12.jpg?AWSAccessKeyId=ASIAJPBDBTBJLCJG6F5Q&Expires=1385050578&Signature=RyMo/loFtkqncHVGsA7WanE6Psc%3D&x-amz-security-token=AQoDYXdzENf//////////wEawAIsrHO97KTEcDp4VTgsK9eAevLfqg5Js7vd%2BUbaraYA6adb6lIiXIyI8abnY4%2B3z6FktlO3McGF8vpqkz4f9ZVGpL3yS2AzLiXd844X2rw%2B%2BmehBVyfXA1o1dMftl50cyghdtVxA/N5xrBCFTbXIPzCclniuGHIFdHjtJZsEZ10AHRbVsYCI7R5%2BmCDYP4/irsVg7Jw%2BFGmSm1L29pwCmjRSw%2BvxcnRf8m6enXob9O2a8OoKkElJC2vbsOzlsclb6gaDfrpC1lLz5TDUdtuY9cuvHNN7E9GXn3ikG9/UtRxwFlpFjoPH%2Ba2XK42xIRb3nDvq2SEyje0WVcpKpImYNcQlKAzCCGWwhtvbArrBFo7ltEZZzoo/LzKox4TwvHxRfWQ1/a14ifuQXzYyEXD9fEfs06hMEnKw38sZgpwEjJfIiDTm7iUBQ%3D%3D")
userdg.save!

usersz = User.create(first_name: "Sharif", last_name:"Zu'bi", username: "Sharif", email: "sharif@sharif.com", age: 22, gender: "Male", location: "London", plan: "premium", password: "password", confirmed_at: DateTime.now, tagline: "Ethnic origin: ARRAYbian", bio:  "I know Cara Delevigne...so you better be good-looking. And possibly Columbian. I Like Twirls and Haribo, so if you're sweet, maybe we'll get along. Must like 'Arabia'.", avatar: "https://s3-eu-west-1.amazonaws.com/wdi-dating-production/uploads/static/gallery_ga_200x200_13.jpg?AWSAccessKeyId=ASIAJPBDBTBJLCJG6F5Q&Expires=1385050615&Signature=Zqx8Tr90GrUCjZFnlhXiKOSQhSA%3D&x-amz-security-token=AQoDYXdzENf//////////wEawAIsrHO97KTEcDp4VTgsK9eAevLfqg5Js7vd%2BUbaraYA6adb6lIiXIyI8abnY4%2B3z6FktlO3McGF8vpqkz4f9ZVGpL3yS2AzLiXd844X2rw%2B%2BmehBVyfXA1o1dMftl50cyghdtVxA/N5xrBCFTbXIPzCclniuGHIFdHjtJZsEZ10AHRbVsYCI7R5%2BmCDYP4/irsVg7Jw%2BFGmSm1L29pwCmjRSw%2BvxcnRf8m6enXob9O2a8OoKkElJC2vbsOzlsclb6gaDfrpC1lLz5TDUdtuY9cuvHNN7E9GXn3ikG9/UtRxwFlpFjoPH%2Ba2XK42xIRb3nDvq2SEyje0WVcpKpImYNcQlKAzCCGWwhtvbArrBFo7ltEZZzoo/LzKox4TwvHxRfWQ1/a14ifuQXzYyEXD9fEfs06hMEnKw38sZgpwEjJfIiDTm7iUBQ%3D%3D")
usersz.save!

userjd = User.create(first_name: "Julien", last_name:"Deslangles-ahtoolongIcan'tbebothered", username: "Julien", email: "julien@julien.com", age: 29, gender: "Male", location: "London", plan: "premium", password: "password", confirmed_at: DateTime.now, tagline: "Seriously?", bio: "No, really.", avatar: "https://s3-eu-west-1.amazonaws.com/wdi-dating-production/uploads/static/gallery_ga_200x200_14.jpg?AWSAccessKeyId=ASIAJPBDBTBJLCJG6F5Q&Expires=1385050647&Signature=%2Bwkrp3TdmQFWS84S0cyF6xFC3IQ%3D&x-amz-security-token=AQoDYXdzENf//////////wEawAIsrHO97KTEcDp4VTgsK9eAevLfqg5Js7vd%2BUbaraYA6adb6lIiXIyI8abnY4%2B3z6FktlO3McGF8vpqkz4f9ZVGpL3yS2AzLiXd844X2rw%2B%2BmehBVyfXA1o1dMftl50cyghdtVxA/N5xrBCFTbXIPzCclniuGHIFdHjtJZsEZ10AHRbVsYCI7R5%2BmCDYP4/irsVg7Jw%2BFGmSm1L29pwCmjRSw%2BvxcnRf8m6enXob9O2a8OoKkElJC2vbsOzlsclb6gaDfrpC1lLz5TDUdtuY9cuvHNN7E9GXn3ikG9/UtRxwFlpFjoPH%2Ba2XK42xIRb3nDvq2SEyje0WVcpKpImYNcQlKAzCCGWwhtvbArrBFo7ltEZZzoo/LzKox4TwvHxRfWQ1/a14ifuQXzYyEXD9fEfs06hMEnKw38sZgpwEjJfIiDTm7iUBQ%3D%3D")
userjd.save!

userml = User.create(first_name: "Maloney", last_name:"Liu", username: "Maloney", email: "maloney@maloney.com", age: 28, gender: "Female", location: "London", plan: "premium", password: "password", confirmed_at: DateTime.now, tagline: "Could you be the SpongeBob to my Patrick?",   bio:
    "I'm Baloney. I mean, Mel. I mean, Maloney - whatever. Make sure I get my coffee in the morning and there will be no problems!",   avatar: "https://s3-eu-west-1.amazonaws.com/wdi-dating-production/uploads/static/gallery_ga_200x200_15.jpg?AWSAccessKeyId=ASIAJPBDBTBJLCJG6F5Q&Expires=1385050675&Signature=7J%2BJA6C9/fjtLnjalnEHzFb3eaw%3D&x-amz-security-token=AQoDYXdzENf//////////wEawAIsrHO97KTEcDp4VTgsK9eAevLfqg5Js7vd%2BUbaraYA6adb6lIiXIyI8abnY4%2B3z6FktlO3McGF8vpqkz4f9ZVGpL3yS2AzLiXd844X2rw%2B%2BmehBVyfXA1o1dMftl50cyghdtVxA/N5xrBCFTbXIPzCclniuGHIFdHjtJZsEZ10AHRbVsYCI7R5%2BmCDYP4/irsVg7Jw%2BFGmSm1L29pwCmjRSw%2BvxcnRf8m6enXob9O2a8OoKkElJC2vbsOzlsclb6gaDfrpC1lLz5TDUdtuY9cuvHNN7E9GXn3ikG9/UtRxwFlpFjoPH%2Ba2XK42xIRb3nDvq2SEyje0WVcpKpImYNcQlKAzCCGWwhtvbArrBFo7ltEZZzoo/LzKox4TwvHxRfWQ1/a14ifuQXzYyEXD9fEfs06hMEnKw38sZgpwEjJfIiDTm7iUBQ%3D%3D")
userml.save!

userck = User.create(first_name: "Clemens", last_name:"Kazda", username: "Clemens", email: "clemens@clemens.com", age: 32, gender: "Male", location: "London", plan: "premium", password: "password", confirmed_at: DateTime.now, tagline: "Have you seen my cool watch?",  bio:
    "Green trousers are the way to go. If you had Snoogd me before, I wouldn't have to be on here. Btw, does your hold need unloading?",  avatar: "https://s3-eu-west-1.amazonaws.com/wdi-dating-production/uploads/static/gallery_ga_200x200_16.jpg?AWSAccessKeyId=ASIAJPBDBTBJLCJG6F5Q&Expires=1385050713&Signature=RPwjqKPZigW77CP50elhV8SE3ZY%3D&x-amz-security-token=AQoDYXdzENf//////////wEawAIsrHO97KTEcDp4VTgsK9eAevLfqg5Js7vd%2BUbaraYA6adb6lIiXIyI8abnY4%2B3z6FktlO3McGF8vpqkz4f9ZVGpL3yS2AzLiXd844X2rw%2B%2BmehBVyfXA1o1dMftl50cyghdtVxA/N5xrBCFTbXIPzCclniuGHIFdHjtJZsEZ10AHRbVsYCI7R5%2BmCDYP4/irsVg7Jw%2BFGmSm1L29pwCmjRSw%2BvxcnRf8m6enXob9O2a8OoKkElJC2vbsOzlsclb6gaDfrpC1lLz5TDUdtuY9cuvHNN7E9GXn3ikG9/UtRxwFlpFjoPH%2Ba2XK42xIRb3nDvq2SEyje0WVcpKpImYNcQlKAzCCGWwhtvbArrBFo7ltEZZzoo/LzKox4TwvHxRfWQ1/a14ifuQXzYyEXD9fEfs06hMEnKw38sZgpwEjJfIiDTm7iUBQ%3D%3D")
userck.save!

userdm = User.create(first_name: "Daida", last_name:"Medina", username: "Daida", email: "daida@daida.com", age: 28, gender: "Female", location: "London", plan: "premium", password: "password", confirmed_at: DateTime.now, tagline:  "Me gusta la música y conciertos.", bio: "Mi llamo Daida. YO soy español. Realmente. Honestamente." , avatar: "https://s3-eu-west-1.amazonaws.com/wdi-dating-production/uploads/static/gallery_ga_200x200_17.jpg?AWSAccessKeyId=ASIAJPBDBTBJLCJG6F5Q&Expires=1385050745&Signature=hVXYZibBN0nGl4b15qP%2BKb7OfMw%3D&x-amz-security-token=AQoDYXdzENf//////////wEawAIsrHO97KTEcDp4VTgsK9eAevLfqg5Js7vd%2BUbaraYA6adb6lIiXIyI8abnY4%2B3z6FktlO3McGF8vpqkz4f9ZVGpL3yS2AzLiXd844X2rw%2B%2BmehBVyfXA1o1dMftl50cyghdtVxA/N5xrBCFTbXIPzCclniuGHIFdHjtJZsEZ10AHRbVsYCI7R5%2BmCDYP4/irsVg7Jw%2BFGmSm1L29pwCmjRSw%2BvxcnRf8m6enXob9O2a8OoKkElJC2vbsOzlsclb6gaDfrpC1lLz5TDUdtuY9cuvHNN7E9GXn3ikG9/UtRxwFlpFjoPH%2Ba2XK42xIRb3nDvq2SEyje0WVcpKpImYNcQlKAzCCGWwhtvbArrBFo7ltEZZzoo/LzKox4TwvHxRfWQ1/a14ifuQXzYyEXD9fEfs06hMEnKw38sZgpwEjJfIiDTm7iUBQ%3D%3D")
userdm.save!

userrr = User.create(first_name: "Ralph", last_name:"Reid", username: "Ralph", email: "ralph@ralph.com", age: 35, gender: "Male", location: "London", plan: "premium", password: "password", confirmed_at: DateTime.now, tagline: "Do you have sensible walking shoes?", bio: "Hey, I'm Ralph. Stop by my place and I'll take you for a ride on my scooter. Gotta keep scootin', man!", avatar: "https://s3-eu-west-1.amazonaws.com/wdi-dating-production/uploads/static/gallery_ga_200x200_18.jpg?AWSAccessKeyId=ASIAJPBDBTBJLCJG6F5Q&Expires=1385050774&Signature=J/CkcQDPzVg0TRptz%2BYWXw9M/Wo%3D&x-amz-security-token=AQoDYXdzENf//////////wEawAIsrHO97KTEcDp4VTgsK9eAevLfqg5Js7vd%2BUbaraYA6adb6lIiXIyI8abnY4%2B3z6FktlO3McGF8vpqkz4f9ZVGpL3yS2AzLiXd844X2rw%2B%2BmehBVyfXA1o1dMftl50cyghdtVxA/N5xrBCFTbXIPzCclniuGHIFdHjtJZsEZ10AHRbVsYCI7R5%2BmCDYP4/irsVg7Jw%2BFGmSm1L29pwCmjRSw%2BvxcnRf8m6enXob9O2a8OoKkElJC2vbsOzlsclb6gaDfrpC1lLz5TDUdtuY9cuvHNN7E9GXn3ikG9/UtRxwFlpFjoPH%2Ba2XK42xIRb3nDvq2SEyje0WVcpKpImYNcQlKAzCCGWwhtvbArrBFo7ltEZZzoo/LzKox4TwvHxRfWQ1/a14ifuQXzYyEXD9fEfs06hMEnKw38sZgpwEjJfIiDTm7iUBQ%3D%3D")
userrr.save!

userew = User.create(first_name: "Emma", last_name:"Walker", username: "Emma", email: "emma@emma.com", age: 21, gender: "Female", location: "London", plan: "premium", password: "password", confirmed_at: DateTime.now, tagline: "Er, I have a boyfriend...",  bio:
    "So, Sharif, please stop cracking onto me.", avatar: "https://s3-eu-west-1.amazonaws.com/wdi-dating-production/uploads/static/gallery_ga_200x200_19.jpg?AWSAccessKeyId=ASIAJPBDBTBJLCJG6F5Q&Expires=1385050815&Signature=qDJf5FuokaqLz638z8sv6zBJoS8%3D&x-amz-security-token=AQoDYXdzENf//////////wEawAIsrHO97KTEcDp4VTgsK9eAevLfqg5Js7vd%2BUbaraYA6adb6lIiXIyI8abnY4%2B3z6FktlO3McGF8vpqkz4f9ZVGpL3yS2AzLiXd844X2rw%2B%2BmehBVyfXA1o1dMftl50cyghdtVxA/N5xrBCFTbXIPzCclniuGHIFdHjtJZsEZ10AHRbVsYCI7R5%2BmCDYP4/irsVg7Jw%2BFGmSm1L29pwCmjRSw%2BvxcnRf8m6enXob9O2a8OoKkElJC2vbsOzlsclb6gaDfrpC1lLz5TDUdtuY9cuvHNN7E9GXn3ikG9/UtRxwFlpFjoPH%2Ba2XK42xIRb3nDvq2SEyje0WVcpKpImYNcQlKAzCCGWwhtvbArrBFo7ltEZZzoo/LzKox4TwvHxRfWQ1/a14ifuQXzYyEXD9fEfs06hMEnKw38sZgpwEjJfIiDTm7iUBQ%3D%3D")
userew.save!

usernm = User.create(first_name: "Neel", last_name:"Mistry", username: "Neel", email: "neel@neel.com", age: 21, gender: "Female", location: "London", plan: "premium", password: "password", confirmed_at: DateTime.now, tagline: "Mistry by name; mystery by nature", bio: "I'm cool Neel. I'm cool because of the way I look and act. If you want to know a cool guy, send me a pull request ;-). By the way I like sushi.", avatar: "https://s3-eu-west-1.amazonaws.com/wdi-dating-production/uploads/static/gallery_ga_200x200_20.jpg?AWSAccessKeyId=ASIAJPBDBTBJLCJG6F5Q&Expires=1385050860&Signature=aYfsBKUO1lddp5uQTdXXSYpItf0%3D&x-amz-security-token=AQoDYXdzENf//////////wEawAIsrHO97KTEcDp4VTgsK9eAevLfqg5Js7vd%2BUbaraYA6adb6lIiXIyI8abnY4%2B3z6FktlO3McGF8vpqkz4f9ZVGpL3yS2AzLiXd844X2rw%2B%2BmehBVyfXA1o1dMftl50cyghdtVxA/N5xrBCFTbXIPzCclniuGHIFdHjtJZsEZ10AHRbVsYCI7R5%2BmCDYP4/irsVg7Jw%2BFGmSm1L29pwCmjRSw%2BvxcnRf8m6enXob9O2a8OoKkElJC2vbsOzlsclb6gaDfrpC1lLz5TDUdtuY9cuvHNN7E9GXn3ikG9/UtRxwFlpFjoPH%2Ba2XK42xIRb3nDvq2SEyje0WVcpKpImYNcQlKAzCCGWwhtvbArrBFo7ltEZZzoo/LzKox4TwvHxRfWQ1/a14ifuQXzYyEXD9fEfs06hMEnKw38sZgpwEjJfIiDTm7iUBQ%3D%3D")
usernm.save!

usergm = User.create(first_name: "Gordon", last_name:"MacRae", username: "Gordon", email: "gordon@gordon.com", age: 26, gender: "Male", location: "London", plan: "premium", password: "password", confirmed_at: DateTime.now, tagline:  "Need loo roll, or teabags?", bio:
    "No? Great! Because I'm tired of these prissy WDI students ordering me about like some skivvy. I'm better than that.", avatar: "https://s3-eu-west-1.amazonaws.com/wdi-dating-production/uploads/static/gallery_ga_200x200_21.jpg?AWSAccessKeyId=ASIAJPBDBTBJLCJG6F5Q&Expires=1385050891&Signature=7O2U0gFQA0QngeqFQkykkgNl7ds%3D&x-amz-security-token=AQoDYXdzENf//////////wEawAIsrHO97KTEcDp4VTgsK9eAevLfqg5Js7vd%2BUbaraYA6adb6lIiXIyI8abnY4%2B3z6FktlO3McGF8vpqkz4f9ZVGpL3yS2AzLiXd844X2rw%2B%2BmehBVyfXA1o1dMftl50cyghdtVxA/N5xrBCFTbXIPzCclniuGHIFdHjtJZsEZ10AHRbVsYCI7R5%2BmCDYP4/irsVg7Jw%2BFGmSm1L29pwCmjRSw%2BvxcnRf8m6enXob9O2a8OoKkElJC2vbsOzlsclb6gaDfrpC1lLz5TDUdtuY9cuvHNN7E9GXn3ikG9/UtRxwFlpFjoPH%2Ba2XK42xIRb3nDvq2SEyje0WVcpKpImYNcQlKAzCCGWwhtvbArrBFo7ltEZZzoo/LzKox4TwvHxRfWQ1/a14ifuQXzYyEXD9fEfs06hMEnKw38sZgpwEjJfIiDTm7iUBQ%3D%3D")
usergm.save!

userjc = User.create(first_name: "Jon", last_name:"Chamber", username: "Jon", email: "jon@jon.com", age: 32, gender: "Male", location: "London", plan: "premium", password: "password", confirmed_at: DateTime.now, tagline:  "I can do you a robot or a caffeinated soft drink: your choice.",   bio:
    "Hi, I'm Jon and I want to really get inside your basal ganglia (that's not a euphemism). I've had some bad experiences with the recent theft of a bicycle, but I won't mind if you steal my heart.",   avatar: "https://s3-eu-west-1.amazonaws.com/wdi-dating-production/uploads/static/gallery_ga_200x200_22.jpg?AWSAccessKeyId=ASIAJPBDBTBJLCJG6F5Q&Expires=1385050920&Signature=zhzLOcNCIbib/nzLlcc8UPlXqc8%3D&x-amz-security-token=AQoDYXdzENf//////////wEawAIsrHO97KTEcDp4VTgsK9eAevLfqg5Js7vd%2BUbaraYA6adb6lIiXIyI8abnY4%2B3z6FktlO3McGF8vpqkz4f9ZVGpL3yS2AzLiXd844X2rw%2B%2BmehBVyfXA1o1dMftl50cyghdtVxA/N5xrBCFTbXIPzCclniuGHIFdHjtJZsEZ10AHRbVsYCI7R5%2BmCDYP4/irsVg7Jw%2BFGmSm1L29pwCmjRSw%2BvxcnRf8m6enXob9O2a8OoKkElJC2vbsOzlsclb6gaDfrpC1lLz5TDUdtuY9cuvHNN7E9GXn3ikG9/UtRxwFlpFjoPH%2Ba2XK42xIRb3nDvq2SEyje0WVcpKpImYNcQlKAzCCGWwhtvbArrBFo7ltEZZzoo/LzKox4TwvHxRfWQ1/a14ifuQXzYyEXD9fEfs06hMEnKw38sZgpwEjJfIiDTm7iUBQ%3D%3D")
userjc.save!

userpc = User.create(first_name: "Paul", last_name:"Connor", username: "Paul", email: "paul@paul.com", age: 25, gender: "Male", location: "London", plan: "premium", password: "password", confirmed_at: DateTime.now, tagline:  "I order a great pizza.", bio:  "I don't do much work, but pizza - now, if you want pizza, that I can arrange.", avatar: "https://s3-eu-west-1.amazonaws.com/wdi-dating-production/uploads/static/gallery_ga_200x200_23.jpg?AWSAccessKeyId=ASIAJPBDBTBJLCJG6F5Q&Expires=1385050947&Signature=zZFuDRwnEgAviXL8S3%2B5r5OFPyo%3D&x-amz-security-token=AQoDYXdzENf//////////wEawAIsrHO97KTEcDp4VTgsK9eAevLfqg5Js7vd%2BUbaraYA6adb6lIiXIyI8abnY4%2B3z6FktlO3McGF8vpqkz4f9ZVGpL3yS2AzLiXd844X2rw%2B%2BmehBVyfXA1o1dMftl50cyghdtVxA/N5xrBCFTbXIPzCclniuGHIFdHjtJZsEZ10AHRbVsYCI7R5%2BmCDYP4/irsVg7Jw%2BFGmSm1L29pwCmjRSw%2BvxcnRf8m6enXob9O2a8OoKkElJC2vbsOzlsclb6gaDfrpC1lLz5TDUdtuY9cuvHNN7E9GXn3ikG9/UtRxwFlpFjoPH%2Ba2XK42xIRb3nDvq2SEyje0WVcpKpImYNcQlKAzCCGWwhtvbArrBFo7ltEZZzoo/LzKox4TwvHxRfWQ1/a14ifuQXzYyEXD9fEfs06hMEnKw38sZgpwEjJfIiDTm7iUBQ%3D%3D")
userpc.save!

userrf = User.create(first_name: "Rob", last_name:"Forbes", username: "Rob", email: "rob@rob.com", age: 21, gender: "Male", location: "London", plan: "premium", password: "password", confirmed_at: DateTime.now, tagline:  "So I implemented this artificial intelligence thing...", bio:  "..and used it to make a girlfriend, so I don't really need you. As you can see I'm busy, so...", avatar: "https://s3-eu-west-1.amazonaws.com/wdi-dating-production/uploads/static/gallery_ga_200x200_24.jpg?AWSAccessKeyId=ASIAJPBDBTBJLCJG6F5Q&Expires=1385050972&Signature=NS5zwunq46YJ6jQt3oQ6G9hob3o%3D&x-amz-security-token=AQoDYXdzENf//////////wEawAIsrHO97KTEcDp4VTgsK9eAevLfqg5Js7vd%2BUbaraYA6adb6lIiXIyI8abnY4%2B3z6FktlO3McGF8vpqkz4f9ZVGpL3yS2AzLiXd844X2rw%2B%2BmehBVyfXA1o1dMftl50cyghdtVxA/N5xrBCFTbXIPzCclniuGHIFdHjtJZsEZ10AHRbVsYCI7R5%2BmCDYP4/irsVg7Jw%2BFGmSm1L29pwCmjRSw%2BvxcnRf8m6enXob9O2a8OoKkElJC2vbsOzlsclb6gaDfrpC1lLz5TDUdtuY9cuvHNN7E9GXn3ikG9/UtRxwFlpFjoPH%2Ba2XK42xIRb3nDvq2SEyje0WVcpKpImYNcQlKAzCCGWwhtvbArrBFo7ltEZZzoo/LzKox4TwvHxRfWQ1/a14ifuQXzYyEXD9fEfs06hMEnKw38sZgpwEjJfIiDTm7iUBQ%3D%3D")
userrf.save!

userab = User.create(first_name: "Adam", last_name:"Buchan", username: "Adam", email: "adam@adam.com", age: 32, gender: "Male", location: "London", plan: "premium", password: "password", confirmed_at: DateTime.now, tagline: "Just give me a parka and an estate agent, and I'm happy as Larry. Whoever he is...", bio:
    "aDAYUMM girl, you gotta be kidding me! You're so fly, you can tell what the weather's like before the rest of us.    Hey, my name's Adam, and I'm a budding programmer. I love padded jackets and house-hunting.", avatar: "https://s3-eu-west-1.amazonaws.com/wdi-dating-production/uploads/static/gallery_ga_200x200_25.jpg?AWSAccessKeyId=ASIAJPBDBTBJLCJG6F5Q&Expires=1385051006&Signature=O0ZiQYAQdw/nQ1aPQZFIuNWOyIg%3D&x-amz-security-token=AQoDYXdzENf//////////wEawAIsrHO97KTEcDp4VTgsK9eAevLfqg5Js7vd%2BUbaraYA6adb6lIiXIyI8abnY4%2B3z6FktlO3McGF8vpqkz4f9ZVGpL3yS2AzLiXd844X2rw%2B%2BmehBVyfXA1o1dMftl50cyghdtVxA/N5xrBCFTbXIPzCclniuGHIFdHjtJZsEZ10AHRbVsYCI7R5%2BmCDYP4/irsVg7Jw%2BFGmSm1L29pwCmjRSw%2BvxcnRf8m6enXob9O2a8OoKkElJC2vbsOzlsclb6gaDfrpC1lLz5TDUdtuY9cuvHNN7E9GXn3ikG9/UtRxwFlpFjoPH%2Ba2XK42xIRb3nDvq2SEyje0WVcpKpImYNcQlKAzCCGWwhtvbArrBFo7ltEZZzoo/LzKox4TwvHxRfWQ1/a14ifuQXzYyEXD9fEfs06hMEnKw38sZgpwEjJfIiDTm7iUBQ%3D%3D")
userab.save!

userjw =  User.create(first_name: "Jamie", last_name:"Wallace", username: "Jamie", email: "jamie@jamie.com", age: 38, gender: "Male", location: "London", plan: "premium", password: "password", confirmed_at: DateTime.now, tagline: "You go on ahead - I'll catch you up.", bio:   "Like a game of 'Where's Wallace'; keep your eye on me, or I might just disappear. If you don't like cycling, we can WalkIt.", avatar: "https://s3-eu-west-1.amazonaws.com/wdi-dating-production/uploads/static/jamiesml.jpg?AWSAccessKeyId=ASIAJPBDBTBJLCJG6F5Q&Expires=1385051304&Signature=g8K07oiIyZ%2BqsgPi8%2BFfs8OC4vs%3D&x-amz-security-token=AQoDYXdzENf//////////wEawAIsrHO97KTEcDp4VTgsK9eAevLfqg5Js7vd%2BUbaraYA6adb6lIiXIyI8abnY4%2B3z6FktlO3McGF8vpqkz4f9ZVGpL3yS2AzLiXd844X2rw%2B%2BmehBVyfXA1o1dMftl50cyghdtVxA/N5xrBCFTbXIPzCclniuGHIFdHjtJZsEZ10AHRbVsYCI7R5%2BmCDYP4/irsVg7Jw%2BFGmSm1L29pwCmjRSw%2BvxcnRf8m6enXob9O2a8OoKkElJC2vbsOzlsclb6gaDfrpC1lLz5TDUdtuY9cuvHNN7E9GXn3ikG9/UtRxwFlpFjoPH%2Ba2XK42xIRb3nDvq2SEyje0WVcpKpImYNcQlKAzCCGWwhtvbArrBFo7ltEZZzoo/LzKox4TwvHxRfWQ1/a14ifuQXzYyEXD9fEfs06hMEnKw38sZgpwEjJfIiDTm7iUBQ%3D%3D")